blank_issues_enabled: false
contact_links:
  - name: â“ Questions
    url: https://github.com/zonxorg/zonxdocs/discussions/new?category=q-a
    about: Please use the community forum for help and questions regarding Zonx Docs
  - name: ğŸ’¡ Feature requests and ideas
    url: https://github.com/zonxorg/zonxdocs/discussions/new?category=feature-requests
    about: Please vote for and post new feature ideas in the community forum
  - name: ğŸ“– Documentation
    url: https://zonxdocs.pages.dev/docs/
    about: A great place to find instructions and answers on how to get the most out of your Zonx Docs themed site
